# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(960, 582)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tab_widget = QtGui.QTabWidget(self.centralwidget)
        self.tab_widget.setGeometry(QtCore.QRect(0, 0, 961, 511))
        self.tab_widget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab_canvas = QtGui.QWidget()
        self.tab_canvas.setObjectName(_fromUtf8("tab_canvas"))
        self.label_2 = QtGui.QLabel(self.tab_canvas)
        self.label_2.setGeometry(QtCore.QRect(260, 420, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_count = QtGui.QLabel(self.tab_canvas)
        self.label_count.setGeometry(QtCore.QRect(450, 200, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_count.setFont(font)
        self.label_count.setText(_fromUtf8(""))
        self.label_count.setObjectName(_fromUtf8("label_count"))
        self.label_score = QtGui.QLabel(self.tab_canvas)
        self.label_score.setGeometry(QtCore.QRect(310, 370, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_score.setFont(font)
        self.label_score.setText(_fromUtf8(""))
        self.label_score.setObjectName(_fromUtf8("label_score"))
        self.widget_canvas = QtGui.QWidget(self.tab_canvas)
        self.widget_canvas.setEnabled(False)
        self.widget_canvas.setGeometry(QtCore.QRect(20, 20, 911, 371))
        self.widget_canvas.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.widget_canvas.setObjectName(_fromUtf8("widget_canvas"))
        self.label = QtGui.QLabel(self.tab_canvas)
        self.label.setGeometry(QtCore.QRect(810, 420, 111, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.combo_box = QtGui.QComboBox(self.tab_canvas)
        self.combo_box.setGeometry(QtCore.QRect(150, 420, 74, 22))
        self.combo_box.setObjectName(_fromUtf8("combo_box"))
        self.combo_box.addItem(_fromUtf8(""))
        self.combo_box.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.tab_canvas)
        self.label_3.setGeometry(QtCore.QRect(80, 420, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.tab_widget.addTab(self.tab_canvas, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_img = QtGui.QLabel(self.tab_2)
        self.label_img.setGeometry(QtCore.QRect(0, 0, 531, 481))
        self.label_img.setObjectName(_fromUtf8("label_img"))
        self.combo_box_mm = QtGui.QComboBox(self.tab_2)
        self.combo_box_mm.setGeometry(QtCore.QRect(760, 60, 121, 22))
        self.combo_box_mm.setObjectName(_fromUtf8("combo_box_mm"))
        self.combo_box_mm.addItem(_fromUtf8(""))
        self.combo_box_mm.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(710, 100, 46, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.combo_box_click = QtGui.QComboBox(self.tab_2)
        self.combo_box_click.setGeometry(QtCore.QRect(760, 100, 121, 22))
        self.combo_box_click.setObjectName(_fromUtf8("combo_box_click"))
        self.combo_box_click.addItem(_fromUtf8(""))
        self.combo_box_click.addItem(_fromUtf8(""))
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(620, 60, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(680, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.combo_box_minimize = QtGui.QComboBox(self.tab_2)
        self.combo_box_minimize.setGeometry(QtCore.QRect(760, 140, 121, 22))
        self.combo_box_minimize.setObjectName(_fromUtf8("combo_box_minimize"))
        self.combo_box_minimize.addItem(_fromUtf8(""))
        self.combo_box_minimize.addItem(_fromUtf8(""))
        self.combo_box_closew = QtGui.QComboBox(self.tab_2)
        self.combo_box_closew.setGeometry(QtCore.QRect(760, 180, 121, 22))
        self.combo_box_closew.setObjectName(_fromUtf8("combo_box_closew"))
        self.combo_box_closew.addItem(_fromUtf8(""))
        self.combo_box_closew.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(640, 180, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.button_restore_def = QtGui.QPushButton(self.tab_2)
        self.button_restore_def.setGeometry(QtCore.QRect(770, 430, 111, 23))
        self.button_restore_def.setObjectName(_fromUtf8("button_restore_def"))
        self.button_save_conf = QtGui.QPushButton(self.tab_2)
        self.button_save_conf.setGeometry(QtCore.QRect(620, 430, 111, 23))
        self.button_save_conf.setObjectName(_fromUtf8("button_save_conf"))
        self.tab_widget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_data = QtGui.QWidget()
        self.tab_data.setObjectName(_fromUtf8("tab_data"))
        self.text_edit = QtGui.QTextEdit(self.tab_data)
        self.text_edit.setEnabled(True)
        self.text_edit.setGeometry(QtCore.QRect(40, 50, 371, 341))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_edit.setFont(font)
        self.text_edit.setObjectName(_fromUtf8("text_edit"))
        self.text_edit_2 = QtGui.QTextEdit(self.tab_data)
        self.text_edit_2.setEnabled(True)
        self.text_edit_2.setGeometry(QtCore.QRect(540, 50, 371, 341))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_edit_2.setFont(font)
        self.text_edit_2.setObjectName(_fromUtf8("text_edit_2"))
        self.button_load_text = QtGui.QPushButton(self.tab_data)
        self.button_load_text.setGeometry(QtCore.QRect(40, 410, 121, 23))
        self.button_load_text.setObjectName(_fromUtf8("button_load_text"))
        self.tab_widget.addTab(self.tab_data, _fromUtf8(""))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(46, 520, 71, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_leap_status = QtGui.QLabel(self.centralwidget)
        self.label_leap_status.setGeometry(QtCore.QRect(120, 520, 111, 21))
        self.label_leap_status.setText(_fromUtf8(""))
        self.label_leap_status.setObjectName(_fromUtf8("label_leap_status"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Configuration = QtGui.QAction(MainWindow)
        self.actionLoad_Configuration.setObjectName(_fromUtf8("actionLoad_Configuration"))
        self.menuFile.addAction(self.actionLoad_Configuration)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "CANVAS", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Left click to recognize. q for quit. c for clear.</p><p align=\"center\">Templates: T</p></body></html>", None))
        self.label.setText(_translate("MainWindow", "canvas size (900, 400)", None))
        self.combo_box.setItemText(0, _translate("MainWindow", "1 Finger", None))
        self.combo_box.setItemText(1, _translate("MainWindow", "All Fingers", None))
        self.label_3.setText(_translate("MainWindow", "Record: ", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_canvas), _translate("MainWindow", "Canvas", None))
        self.label_img.setText(_translate("MainWindow", "TextLabel", None))
        self.combo_box_mm.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_mm.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.label_4.setText(_translate("MainWindow", "Click", None))
        self.combo_box_click.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_click.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.label_5.setText(_translate("MainWindow", "Mouse movement", None))
        self.label_6.setText(_translate("MainWindow", "Minimize", None))
        self.combo_box_minimize.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_minimize.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.combo_box_closew.setItemText(0, _translate("MainWindow", "gesture 1 (default)", None))
        self.combo_box_closew.setItemText(1, _translate("MainWindow", "gesture 2", None))
        self.label_7.setText(_translate("MainWindow", "Close Window", None))
        self.button_restore_def.setText(_translate("MainWindow", "Restore Defaults", None))
        self.button_save_conf.setText(_translate("MainWindow", "Save Configuration", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_2), _translate("MainWindow", "Tab2", None))
        self.button_load_text.setText(_translate("MainWindow", "load Text", None))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_data), _translate("MainWindow", "Data", None))
        self.label_8.setText(_translate("MainWindow", "LEAP Status", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionLoad_Configuration.setText(_translate("MainWindow", "Load Configuration", None))

